# Generated by Django 5.2.4 on 2025-07-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
