# Generated by Django 5.2.4 on 2025-07-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_pendinguser_delete_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='username',
            field=models.CharField(unique=True),
        ),
    ]
